apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    argocd.argoproj.io/instance: cert-manager
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: kumarar.kharal@thitsaworks.com
    privateKeySecretRef:
      name: letsencrypt
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - http01:
          ingress:
            class: nginx